---
Name: push_config
---
SilverStripe\Core\Injector\Injector:
  Sunnysideup\PushNotifications\Forms\PushProviderField:
    properties:
      registry: '%$Sunnysideup\PushNotifications\Api\PushProvidersRegistry'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'sunnysideup/push-notifications:client/dist/css/push-admin.css'

SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\PushNotifications\Extensions\MemberExtension
SilverStripe\Security\Group:
  extensions:
    - Sunnysideup\PushNotifications\Extensions\GroupExtension
