---
Name: push_config
---
SilverStripe\Core\Injector\Injector:
  Sunnysideup\PushNotifications\Api\PushProvidersRegistry:
    properties:
      providers:
        - Sunnysideup\PushNotifications\Api\Providers\PushNotificationEmail
        - Sunnysideup\PushNotifications\Api\Providers\PushNotificationVapid
  Sunnysideup\PushNotifications\Forms\PushProviderField:
    properties:
      registry: '%$Sunnysideup\PushNotifications\Api\PushProvidersRegistry'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'sunnysideup/push-notifications:client/dist/css/push.css'

SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\PushNotifications\Extensions\MemberExtension


---
After: framework
---
SilverStripe\Control\Director:
  rules:
    'notifications/$Action': '%$Sunnysideup\PushNotifications\Controllers\PushNotificationController'